name: HTML and CSS Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Install dependencies
      run: |
        bundle install
    - name: Test HTML and CSS
      run: |
        bundle exec jekyll build
        bundle exec htmlproofer ./tangtuphuc/CI-CD/pacman/index.html --disable-external --check-html --check-opengraph --check-sri --check-favicon --empty-alt-ignore --url-ignore "/^\/assets\//"
